### PR TITLE
Multimode: transform JS object to React props (JSX)

### PR DESCRIPTION
**Pull request by nimobeeren**
This PR adds a new mode: converting from a JS object to React props, as popularized by UI libraries like [Styled System](https://styled-system.com/table/) and [Chakra UI](https://chakra-ui.com/style-props).

image

A limitation of this implementation is that the input object must have each rule on a new line, otherwise it is interpreted as a single rule. I have experimented with an [approach using eval()](https://github.com/nimobeeren/css-to-js/blob/feature/object-to-props-eval/src/functions/transformToProps.js) but it has some drawbacks (for example, it can't deal with variables in values). Aside from its flaws it is quite an elegant approach in my opinion, so I might give it another shot.

A cool thing I found is how it formats the final result. It directly uses Prettier to format it in exactly the same way as when you write the props on a React component!

I'll create another PR soon that adds transforming from CSS directly to JSX (probably by just composing the two existing transformers). So then we can go CSS => object => JSX. I haven't tried going the other way yet, but I have some ideas :thinking:

Oh and a final note: I renamed the existing `transform.js` to `transformCss2Obj.js`, but that probably also affects how Netlify handles that function. I'm not sure what it's doing with those functions, but I've added that same export to the new transformer. If it's preferred we can keep the original transformer as `transform.js`.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey

Wouldn't it make sense to merge these two into a new branch in this repo and I add you as a contriubutor so you can push?

**Comment by SaraVieira** [comment]
> A cool thing I found is how it formats the final result. It directly uses Prettier to format it in exactly the same way as when you write the props on a React component!

This is really awesome! Also props for adding tests like I didn't 😭

I am also gonna add some on mine as it would be waaay better to test :(

**Comment by nimobeeren** [comment]
@SaraVieira thanks for inviting me as contributor!

I think the easiest would be to close #3 and I'll merge that branch into this one (it already is for the most part). Finally, we can merge this one into master. I initially made two PRs so it would be easier to understand what each of the branches do.

I realized while making this that adding tests is actually really easy, you could even choose to do everything with `toMatchSnapshot()` and it would just fail if the output ever changes. But yay for tests!

**Comment by SaraVieira** [comment]
Sounds good! There are some conflicts, do you want me to take a look or you will?


Again, thank you so much!

**Comment by nimobeeren** [comment]
@SaraVieira I don't mind fixing them, I'm just trying to figure out how to merge master from upstream into my fork. But I'll shout if I can't make it work

**Comment by SaraVieira** [comment]
You can check that out here: https://gist.github.com/CristinaSolana/1885435

**Comment by nimobeeren** [comment]
Looks like it worked! I think it's ready to merge, you can take a look before merging if you want. Otherwise feel free to press the button :heavy_check_mark:

**Comment by SaraVieira** [comment]
Thank you so much! MERGED! I will also add the contributors bot to show you as one!

This is serisouly great

**Comment by SaraVieira** [comment]
@all-contributors please add nimobeeren for code

**Comment by SaraVieira** [comment]
@all-contributors please add nimobeeren for code

**Comment by nimobeeren** [comment]
@SaraVieira awesome! Really cool project! :grin:

**Comment by SaraVieira** [comment]
I just styled the select a bit more, hope you like it
ui

**Pull request merged**
